### ISSUE TITLE
Move parameters with default values to the end of parameter list

### ISSUE THREAD

**Issue by philerooski** [Sage-Bionetworks/synapseforms#29]
There are quite a few functions that have a default parameter somewhere in the middle of the parameter list.

For example: https://github.com/Sage-Bionetworks/synapseforms/blob/0e07344900ff420a3dceb2d09280a5bbfad7b454/R/download-all-submissions.R#L9-L10

This prevents the user from passing any of the subsequent parameters as positional arguments. (Unless, in the example above, they wanted to type out `"SUBMITTED_WAITING_FOR_REVIEW"` before passing group and output_dir as positional arguments).

**Comment by Aryllen** [comment]
That's a good point! Thank you for catching that. I will go through and move those to the end.
