### ISSUE TITLE
download all and get table error

### ISSUE THREAD

**Issue by philerooski** [Sage-Bionetworks/synapseforms#40]
Something is funky about the way arguments are passed to `get_submissions_metadata` within `download_all_and_get_table`. I can call `get_submissions_metadata` just fine but passing the same arguments to `download_all_and_get_table` throws an exception after calling the `get_submissions_metadata` method. I included a screenshot below showing what I mean.

![image](https://user-images.githubusercontent.com/2773709/80017520-93022a00-8489-11ea-9969-58b505d20065.png)

**Comment by philerooski** [comment]
Whoops, I didn't notice that `download_all_and_get_table` calls `download_all_submissions_temp` before `get_submissions_metadata`. So I assume the funky business is happening in `download_all_submissions_temp`.

**Comment by philerooski** [comment]
Ah, the arguments are passed in the incorrect order here: https://github.com/Sage-Bionetworks/synapseforms/blob/master/R/main.R#L31

I recommend always using named arguments within the package itself so that moving things around later doesn't break upstream functions.

**Comment by karawoo** [comment]
Good catch @philerooski. I noticed and fixed a similar issue in #34. Might be worth doing a pass over all of the functions since it seems to be an issue in many places.

**Comment by Aryllen** [comment]
Thanks for catching that! I can go over all the functions later today and see which need to be fixed.

Also, thank you for the tip. Using named arguments would have been a smarter idea since it would have fixed this problem.
