### ISSUE TITLE
Create a tidy table from JSON form data

### ISSUE THREAD

**Issue by philerooski** [Sage-Bionetworks/synapseforms#45]
`download_all_and_get_table` produces a table with a `variable` column and one column for each form. This might be fine for viewing data from a small number of forms on the screen but it's an inconvenient format for querying or munging on.

**Comment by philerooski** [comment]
I actually discovered `make_tidier_table` after I filed this but this type of table is actually _too_ tidy, in the sense that it still has some of the querying/munging issues as `download_all_and_get_table` but in vice versa -- the data is too long rather than too wide.

**Comment by Aryllen** [comment]
This is a difficult issue when trying to generalize to potentially any JSON that could be in the forms services. I believe I went these two routes with the idea that the data is there and if they know what they should be expecting, they can further refine the organization. But yeah, neither of these options are great. I think something that iterates through the file piece by piece would be better.

**Comment by philerooski** [comment]
Closed for the same reason as #46
