### ISSUE TITLE
Support STRING_LIST for json to dataframe conversion

### ISSUE THREAD

**Issue by philerooski** [Sage-Bionetworks/synapseforms#46]
Resolving #45 will introduce a problem of its own when converting JSON forms to tabular format. JSON data from the same FormGroup may be converted to tabular formats with inconsistent schemas. This is because JSON elements that contain a variable number of values (like "select all that apply" type questions) end up with a variable number of columns. When creating a table from all available FormData this initially isn't an issue because we row bind each of the flattened json. But that becomes problematic when trying to output that dataframe to a preexisting table -- one that might have been created with a slightly different schema because of the "select all that apply" issue mentioned above. For example.

I have one form in my form group. It contains a JSON with this element: `"favoriteColor": ["blue", "red"]`. I download all forms and convert to a tabular data and store to a Synapse table with the schema `favoriteColor1,favoriteColor2`. Someone then submits a new form with the element  `"favoriteColor": ["blue", "red", "green"]`. Now my schema is `favoriteColor1,favoriteColor2,favoriteColor3` and Synapse rejects my table update.

One potential solution is to only create columns for top level elements, and any values will be the raw json of the "child" elements. So in the example above our table would look like:

| FormId | favoriteColor            |
|--------|--------------------------|
| 1      | ["blue", "red"]          |
| 2      | ["blue", "red", "green"] |

But this gets problematic when we get JSON forms that produce tables like this:

| FormId | favorite            |
|--------|--------------------------|
| 1      | {"color": ["blue", "red"], "animal": ["dog"]}          |
| 2      | {"color": ["blue", "red", "green"], "animal": ["cat"]} |

So to deal with problematic JSON hierarchy issues I propose we use STRING_LIST column types. This is a new column type that essentially only contains flat JSON lists like `["blue", "red", "green"]`. When converting from JSON to tabular format, we can expand the hierarchy until we encounter a flat list like this (which, not so coincidentally, is the type of element produced by "select all that apply" type questions). Any additional hierarchy could be made into a new column using snake case notation. So our table above would become:

| FormId | favorite_color           | favorite_animal |
|--------|--------------------------|-----------------|
| 1      | ["blue", "red"]          | ["dog"]         |
| 2      | ["blue", "red", "green"] | ["cat"]         |

This is a hybrid approach between fully expanding everything (producing columns like favoriteColor1, favoriteColor2, ..., favoriteAnimal1, ...) and only creating columns for top-level fields and all values are (hierarchical) json blobs.

**Comment by Aryllen** [comment]
Good compromise.

**Comment by philerooski** [comment]
A few sample implementations provided by my colleagues:

James in R:
```
jsonlite::fromJSON(j) %>% 
  purrr::imap_dfr(function(field_vals, field_name) {
    tibble::as_tibble(field_vals) %>% 
      dplyr::rowwise() %>% 
      dplyr::mutate_all(~ jsonlite::toJSON(.)) %>% 
      dplyr::ungroup() %>% 
      dplyr::rename_all(~ stringr::str_c(field_name, ., sep = "_"))
  })
```
![image](https://user-images.githubusercontent.com/2773709/81217235-1bf08980-8f91-11ea-88dc-7de2bf4f5eb6.png)

Tom in Python:
```
pd.json_normalize(example)
temp = temp.applymap(json.dumps)
       favorite.color favorite.animal
             favorite.color favorite.animal
0           ["blue", "red"]         ["dog"]
1  ["blue", "red", "green"]         ["cat"]
```

Kara in R:
```
library("jsonlite")
library("tidyverse")
json <- '
[
  {
    "favorite": {
      "color": ["blue", "red"],
      "animal": ["dog"]
    }
  },
  {
    "favorite": {
      "color": ["blue", "red", "green"],
      "animal": ["cat"]
    }
  }
] 
'
fromJSON(json, simplifyDataFrame = FALSE) %>%
  unlist(recursive = FALSE) %>%
  imap_dfr(function(data, name) {
    set_names(map(data, toJSON), ~ paste(name, .x, sep = "_"))
  })
#> # A tibble: 2 x 2
#>   favorite_color                 favorite_animal
#>   <chr>                          <chr>          
#> 1 "[\"blue\",\"red\"]"           "[\"dog\"]"    
#> 2 "[\"blue\",\"red\",\"green\"]" "[\"cat\"]"
```
> but this only works if the data is nested to a consistent level. based on what i’ve seen in the stop-ad forms, I think a generalized solution for form data probably needs to use while loops or recursion, as the depth at which you reach an array or single value is not always the same. tidyjson may have some tools for this https://github.com/colearendt/tidyjson

**Comment by philerooski** [comment]
After some thought, this isn't really feasible because not all list/array items will be atomic values. We could have a scenario where we have a list of JSON objects, each with their own key/value mapping. For example, a form where you create a new object for each _specimen_ in your experiment. The number of specimens can vary and they each have their own properties. This is essentially a new table with a schema designed for describing specimens. But creating multiple tables to intake a single form, i.e., spreading a single record across multiple tables and/or rows, is complicated to do in a generalizable way and is confusing when all you are trying to do is decide whether to approve or reject a form.
